name: terraform initialization
run-name: terraform install
on:
 push
jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v4.2.2  
     with:
        token: ${{ secrets.TOKEN }}
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
   - name: set hashicorp  
     uses: hashicorp/setup-terraform@v2.0.3
     with:
      terraform-version: 5.48.0
   - name: Generate TF Docs
     uses: terraform-docs/gh-actions@v1.3.0
     with:
      working-dir: .  
   - name: configue git
     run: |
      git config --global user.name 'agarapunaveen'
      git config --global user.email 'agarapunaveen@gmail.com'
   - name: install terraform docs
     uses: terraform-docs/gh-actions@v1.3.0
     with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
   - name: configure AWS credential
     uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      aws-region: us-east-1
   - name: initialize terraform
     run: terraform init
   - name: install docs
     run: sudo snap install terraform-docs
   - name: plan terraform
     run: terraform plan 
   # - name: generate terraform docs
     # run: |
      # chmod +x terraform-docs.sh
      # ./terraform-docs.sh
   - name: apply terraform
     run: terraform apply -auto-approve
 
      
