name: terraform initialization
run-name: terraform install
on:
 push
jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - name: install hashicorp
   - uses: hashicorp/setup-terraform@v2.0.3
     with:
      terraform-version: 5.48.0
   - name: configure AWS credentials
   - uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{ aws_access_key }}
      aws-secret-access-key: ${{ aws_secret_key }}
   - name: initialize terraform
     run: terraform init
      
