name: terraform initialization
run-name: terraform install
on:
 - push
 - pull_request
jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v4.2.2  
   - name: set hashicorp  
     uses: hashicorp/setup-terraform@v2.0.3
     with:
      terraform-version: 5.48.0
   - name: configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      aws-region: us-east-1
   - name: initialize terraform
     run: terraform init
   - name: plan terraform
     run: terraform plan 
   - name: apply terraform
     
     run: |
      if: [ ${{ github.event.pull_request.merged }} == true ]; then
        terraform apply -auto-approve
      else
       echo "please first approve frome the merge request"
      fi 
 
      
